### ISSUE TITLE
Error on package installation

### ISSUE THREAD

**Issue by pankaj3009** [eddelbuettel/dang#2]
While installing from cran, i get the following error
* installing *source* package ‘dang’ ...
** package ‘dang’ successfully unpacked and MD5 sums checked
** libs
g++  -I/usr/share/R/include -DNDEBUG  -I"/home/psharma/R/x86_64-pc-linux-gnu-library/3.4/tidyCpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c checkNonAscii.cpp -o checkNonAscii.o
In file included from /home/psharma/R/x86_64-pc-linux-gnu-library/3.4/tidyCpp/include/tidyCpp:6:0,
                 from checkNonAscii.cpp:28:
/home/psharma/R/x86_64-pc-linux-gnu-library/3.4/tidyCpp/include/tidy/internals.h: In function ‘unsigned int R::Altrep(SEXP)’:
/home/psharma/R/x86_64-pc-linux-gnu-library/3.4/tidyCpp/include/tidy/internals.h:46:56: error: ‘ALTREP’ was not declared in this scope
     inline unsigned int Altrep(SEXP x)       { return (ALTREP(x));           }
                                                        ^~~~~~
/home/psharma/R/x86_64-pc-linux-gnu-library/3.4/tidyCpp/include/tidy/internals.h:46:56: note: suggested alternative: ‘RSTEP’
     inline unsigned int Altrep(SEXP x)       { return (ALTREP(x));           }
                                                        ^~~~~~
                                                        RSTEP
/usr/lib/R/etc/Makeconf:168: recipe for target 'checkNonAscii.o' failed

Any dependency that I might be missing or any other information that i can provide. Thanks for help.

**Comment by eddelbuettel** [comment]
> 3.4

Your R  installation is from a few years ago.  Please try again on a current system.  (Or manually edit out the dependency on tidyCpp from the source of dang; it is only used for one C++ function....)
